name: Deploy to ECS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:

  maven-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image docker
        run: docker build -t meu_usuario_docker/meu_app:${{ github.sha }} .

#      - name: Push Docker image
#        run: |
#          docker tag meu_usuario_docker/meu_app:${{ github.sha }} meu_usuario_docker/meu_app:latest
#          docker push meu_usuario_docker/meu_app:${{ github.sha }}
#          docker push meu_usuario_docker/meu_app:latest

  CD:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

#      - name: Update ECS service
#        run: |
#          aws ecs update-service \
#            --cluster app-cluster \
#            --service meu_app_service \
#            --force-new-deployment
