name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with Maven
        run: mvn clean install -DskipTests=false

  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag api-spring-eureka:$(date +%s)

      - name: Log in to Docker Hub
      - uses: actions/checkout@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t aclecioscruz/api-spring-eureka:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker tag aclecioscruz/api-spring-eureka:${{ github.sha }} aclecioscruz/api-spring-eureka:latest
          docker push aclecioscruz/api-spring-eureka:${{ github.sha }}
          docker push aclecioscruz/api-spring-eureka:latest
