name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t aclecioscruz/api-spring-eureka:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker tag aclecioscruz/api-spring-eureka:${{ github.sha }} aclecioscruz/api-spring-eureka:latest
          docker push aclecioscruz/api-spring-eureka:${{ github.sha }}
          docker push aclecioscruz/api-spring-eureka:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster app-cluster \
            --service meu_app_service \
            --force-new-deployment
